// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB24yXA66pwy5X6g8ZhT4gdaCOy_bkiNq0',
    appId: '1:412757137282:web:b269693337af1b0d3da19b',
    messagingSenderId: '412757137282',
    projectId: 'numonix-bcf6e',
    authDomain: 'numonix-bcf6e.firebaseapp.com',
    storageBucket: 'numonix-bcf6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0-oVXFb7Ujwy7wubBa_ucmJ0oUE-18M',
    appId: '1:412757137282:android:22fcc0a57ed5487d3da19b',
    messagingSenderId: '412757137282',
    projectId: 'numonix-bcf6e',
    storageBucket: 'numonix-bcf6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJ9L70uCHfyEWF2H8D3VkXQ6w3JOjjsI',
    appId: '1:412757137282:ios:c85b4bcfc3842a6c3da19b',
    messagingSenderId: '412757137282',
    projectId: 'numonix-bcf6e',
    storageBucket: 'numonix-bcf6e.firebasestorage.app',
    iosBundleId: 'com.numonix.numonix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJ9L70uCHfyEWF2H8D3VkXQ6w3JOjjsI',
    appId: '1:412757137282:ios:98aa94a933c1dd793da19b',
    messagingSenderId: '412757137282',
    projectId: 'numonix-bcf6e',
    storageBucket: 'numonix-bcf6e.firebasestorage.app',
    iosBundleId: 'com.example.leemcwest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB24yXA66pwy5X6g8ZhT4gdaCOy_bkiNq0',
    appId: '1:412757137282:web:4d7509da918739fc3da19b',
    messagingSenderId: '412757137282',
    projectId: 'numonix-bcf6e',
    authDomain: 'numonix-bcf6e.firebaseapp.com',
    storageBucket: 'numonix-bcf6e.firebasestorage.app',
  );
}
