import 'package:leemcwest/features/authentication/data/rx_post_change_password/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_create_password/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_forget_password/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_login/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_reset_password_otp/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_sign_up/rx.dart';
import 'package:leemcwest/features/authentication/data/rx_post_verify_email/rx.dart';
import 'package:leemcwest/features/authentication/model/login_model.dart';
import 'package:leemcwest/features/authentication/model/otp_pass_model.dart';
import 'package:leemcwest/features/authentication/model/otp_verify_model.dart';
import 'package:leemcwest/features/profile/data/rx_get_faq/rx.dart';
import 'package:leemcwest/features/profile/data/rx_get_profile_data/rx.dart';
import 'package:leemcwest/features/profile/data/rx_post_logout/rx.dart';
import 'package:leemcwest/features/profile/data/rx_post_update_profile/rx.dart';
import 'package:leemcwest/features/profile/model/faq_model.dart';
import 'package:leemcwest/features/profile/model/profile_data_model.dart';
import 'package:leemcwest/features/support/data/rx_post_bug_report/rx.dart';
import 'package:leemcwest/features/support/data/rx_post_contact_support/rx.dart';
import 'package:leemcwest/features/support/data/rx_post_feature_suggestion/rx.dart';
import 'package:rxdart/subjects.dart';
SignUpRx signUpRxObj = SignUpRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
VerifyEmailRX verifyEmailRxObj = VerifyEmailRX(empty: OtpVerifyModel(), dataFetcher: BehaviorSubject<OtpVerifyModel>());
LoginRx loginRxObj = LoginRx(empty: LoginModel(), dataFetcher: BehaviorSubject<LoginModel>());
ForgotPassRx forgotPassRxObj = ForgotPassRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
ResetPassOtpRx resetPassOtpRxObj = ResetPassOtpRx(empty: OtpPassModel(), dataFetcher: BehaviorSubject<OtpPassModel>());
PostResetPasswordRx postResetPasswordRxObj = PostResetPasswordRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
PostChangePasswordRx postChangePasswordRxObj = PostChangePasswordRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
LogoutRx logoutRxObj = LogoutRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
GetOwnProfileRx getOwnProfileRxObj = GetOwnProfileRx(empty: ProfileDataModel(), dataFetcher: BehaviorSubject<ProfileDataModel>());
PostContactSupportRx postContactSupportRxObj = PostContactSupportRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
PostFeatureSuggestionRx postFeatureSuggestionRxObj = PostFeatureSuggestionRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
PostBugReportRx postBugReportRxObj = PostBugReportRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
EditProfileRx editProfileRxObj = EditProfileRx(empty: {}, dataFetcher: BehaviorSubject<Map>());
GetFaqRx getFaqRxObj = GetFaqRx(empty: FaqModel(), dataFetcher: BehaviorSubject<FaqModel>());